version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    container_name: aivec_wp_reverse_proxy
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8888:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: mariadb:10 # or mysql:5.7
    container_name: aivec_wp_mysql
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  phpmyadmin:
    container_name: aivec_wp_pma
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 22222:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 300M
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`wp.pma.localhost`)"
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 8025:8025
    labels:
      - "traefik.http.routers.mailhog.rule=Host(`wp.email.localhost`)"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"

volumes: 
  data: