ARG WORDPRESS_VERSION
FROM wordpress:${WORDPRESS_VERSION:+$WORDPRESS_VERSION-}php8.5-apache

RUN apt update && apt install -y \
    # for wp cli
    default-mysql-client

# Strict error/notice reporting
RUN echo "error_reporting=E_ALL" >> /usr/local/etc/php/php.ini

# Install xdebug for PHP live debugging in vscode
RUN yes | pecl install xdebug-3.5.0
RUN touch /var/www/html/xdebug_log
RUN echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.client_port=9900" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.log=/var/www/html/xdebug_log" >> /usr/local/etc/php/conf.d/xdebug.ini \
    # until an option is added to suppress the `[Step Debug] Could not connect to debugging client.` error message,
    # we set the log_level to 0
    && echo "xdebug.log_level=1" >> /usr/local/etc/php/conf.d/xdebug.ini

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

ARG DOCKER_CONTAINER_CONFIG_FOLDER
ARG DOCKER_CONTAINER_INSTANCE_CONFIG_FILEPATH
ARG HOST_INSTANCE_CONFIG_FILEPATH

COPY src/scripts ${DOCKER_CONTAINER_CONFIG_FOLDER}/scripts
COPY ${HOST_INSTANCE_CONFIG_FILEPATH} ${DOCKER_CONTAINER_INSTANCE_CONFIG_FILEPATH}

RUN sed -i '/^exec "\$\@"/d' /usr/local/bin/docker-entrypoint.sh
RUN echo 'php /wp-docker/scripts/init.php' >> /usr/local/bin/docker-entrypoint.sh
RUN echo 'exec "$@"' >> /usr/local/bin/docker-entrypoint.sh
