services:
  db:
    image: mariadb:10 # or mysql:5.7
    restart: always
    container_name: ${WORDPRESS_DB_HOST}
    networks:
      - local-wp-net
    volumes:
      - data:/var/lib/mysql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-wordpress}
    # labels:
    #   - "traefik.tcp.routers.${DB_HOSTNAME:?error}.entrypoints=mysql"
    #   - "traefik.tcp.routers.${DB_HOSTNAME:?error}.rule=HostSNI(`${DB_HOSTNAME:?error}.localhost`)"
    #   # - "traefik.tcp.services.${DB_HOSTNAME:?error}.loadbalancer.server.port=3306"
volumes: 
  data:
networks:
  local-wp-net:
    name: local-wp-net